### ISSUE TITLE
Support passing options to the connection

### ISSUE THREAD

**Issue by bdusauso** [llxff/coney#10]
As I can see from [RabbitConnection](https://github.com/llxff/coney/blob/master/lib/coney/rabbit_connection.ex#L6) it's not possible to pass other options than `url` and `timeout`  to the connection.
In order to support, for example, SSL, it would be nice to pass these options directly to `AMQP.Connection.open/2`.

Moreover, instead of a _hash_ I think it's more idiomatic to use a _keyword_, like this:

```elixir
config :coney,
  adapter: Coney.RabbitConnection,
  pool_size: 1,
  settings: [
    url: "amqp://guest:guest@localhost",
    timeout: 1000,
   ssl_options: [
         cacertfile: "cacert.pem",
         certfile:   "cert.pem",
         keyfile:    "key.pem",
         verify: :verify_peer,
         fail_if_no_peer_cert: true,
         server_name_indication: :disable
       ]
  ],
  workers: [
    MyApplication.MyConsumer
  ]
# also you can define mapping like this and skip it in consumer module:
  workers: [
    [
      connection: [
        prefetch_count: 10,
        exchange:       {:direct, "my_exchange", durable: true},
        queue:          {"my_queue", durable: true},
        binding:        [routing_key: "routing_key"]
      ],
      worker: MyApplication.MyConsumer
    ]
  ]
```

What do you think ?

**Comment by llxff** [comment]
Hi, would be great to have this.

> instead of a hash I think it's more idiomatic to use a keyword, like this:

I think would be better to leave map because of backward compatibility.

**Comment by bdusauso** [comment]
> Hi, would be great to have this.
> 
I will provide a PR as soon as possible.

> > instead of a hash I think it's more idiomatic to use a keyword, like this:
> 
> I think would be better to leave map because of backward compatibility.

Oh, I see. At the end it's just a matter of consistency and taste 😃

**Comment by llxff** [comment]
Awesome 👍

**Comment by bdusauso** [comment]
See PR #12
